targets:
  dev:
    permissions:
      - user_name: surnay143@gmail.com
        level: CAN_MANAGE

    presets:
      name_prefix: (dev ${workspace.current_user.short_name})
      source_linked_deployment: false